name = "GLODAP_Section_Gridder"
uuid = "45a42bf8-19b1-4728-9874-ba229112bd97"
authors = ["Charles Turner <ct6g18@soton.ac.uk> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
